function [configparams] = getparameters()
%   function to get data structure with all paramters 
%   create custom configuration for all parameters

ds = 2; % 0: KITTI, 1: Malaga, 2: parking
bootstrap_frames = [1,2,3]; %frames for bootstrap
keypoints_min = 100; % minimum number of keypoints, when below reinitialize
max_candidates = 500; % maximum number of candidates to track

%keypoint extraction
harris_minquality = 1e-5; % harris minimum quality (weakest kept score / strongest score)
strongest_init = 1000; % maximum number of keypoints for corner detection
strongest_co = 500;

%tracking
max_bidirectional_error = 1; % maximum bidirectional error KLT tracker
min_displacement_match = 3; % if below, new feature == old keypoint/candidate

%ransac parameters
ransac_numtrials = 8000;
ransac_confidence = 99.999;
error_threshold = 0.2;

%triangulation
furthest_triangulate = 100;
max_repro = 2;
min_angle_deg = 10;
min_consecutive_frames = 8;

% debug and plots
plot_initialization = false; % plot initialization pointcloud
plot_local = true; % plot local trajectory +  current pointcloud
plot_kc = false; % plot number keypoints and candidates
plot_cameras = false; % plot previous and current frame cameras
plot_correspond = false; % plot image with keypoints (green), candidates (red) and new candidates (magenta)
plot_new = false; % plot new triangulations
plot_final = true; % plot complete path

configparams = struct(  "ds", ds, ...
                        "bootstrap_frames", bootstrap_frames, ...
                        "keypoints_min", keypoints_min, ...
                        "max_candidates", max_candidates, ...
                        "harris_minquality", harris_minquality, ...
                        "strongest_init", strongest_init, ...
                        "strongest_co", strongest_co, ...
                        "max_bidirectional_error", max_bidirectional_error, ...
                        "min_displacement_match", min_displacement_match, ...
                        "ransac_numtrials", ransac_numtrials, ...
                        "ransac_confidence", ransac_confidence, ...
                        "error_threshold", error_threshold, ...
                        "furthest_triangulate", furthest_triangulate, ...
                        "max_repro", max_repro, ...
                        "min_angle_deg", min_angle_deg, ...
                        "min_consecutive_frames", min_consecutive_frames, ...
                        "plot_initialization", plot_initialization, ...
                        "plot_local", plot_local, ...
                        "plot_kc", plot_kc, ...
                        "plot_cameras", plot_cameras, ...
                        "plot_correspond", plot_correspond, ...
                        "plot_new", plot_new, ...
                        "plot_final", plot_final);
end

